ARG PYTHON_VERSION=3.9-slim
FROM python:${PYTHON_VERSION}

ARG VERSION=latest

ENV TZ=UTC
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

COPY files/fixtures.json /fixtures.json
COPY files/local_settings.py /etc/patchman/local_settings.py
COPY files/run.sh /run.sh

# hadolint ignore=DL3013,DL3018
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
      curl \
      python3-apt \
      python3-dev \
      libmagic1 \
    && apt-get clean \
    && apt-get autoremove -y \
    && mkdir /configuration \
    && rm -rf \
      /var/lib/apt/lists/* \
      /var/tmp/* \
    && chmod +x /wait \
    && python3 -m pip --no-cache-dir install -U 'pip==22.0.4' \
    && python3 -m pip --no-cache-dir install 'patchman[postgres]==2.0.3'\
    && ln -s /usr/lib/python3/dist-packages/*apt* /usr/local/lib/python3.9/site-packages \
    && useradd patchman \
    && chown patchman: /etc/patchman/local_settings.py \
    && mkdir -p /var/lib/patchman/db \
    && lib=$(python3 -c "import site; print(site.getsitepackages()[0])") \
    && mkdir -p "$lib/run/static" \
    && chown -R patchman: /var/lib/patchman "$lib/run/static" \
    && apt-get remove -y \
      python3-dev

USER patchman
WORKDIR /

EXPOSE 8000

CMD ["sh", "-c", "/wait && /run.sh"]
HEALTHCHECK CMD curl --fail http://localhost:8000 || exit 1

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
