ARG VERSION=3.83.2  # renovate: datasource=docker depName=sonatype/nexus3
FROM sonatype/nexus3:${VERSION}

COPY files/scripts /scripts

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
