# https://raw.githubusercontent.com/tcely/dockerhub-powerdns/master/dnsdist/Dockerfile

FROM alpine:3 AS builder

ARG VERSION

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=DL3003,SC2035
RUN apk add --no-cache \
      boost-dev \
      ca-certificates \
      curl \
      file \
      g++ \
      gnupg \
      jq \
      libedit-dev \
      libsodium-dev \
      lua-dev \
      make \
      net-snmp-dev \
      openssl-dev \
      protobuf-dev \
      re2-dev && \
    [ -n "$VERSION" ] || { curl -sSL 'https://api.github.com/repos/PowerDNS/pdns/tags?per_page=100&page={1,2}' | jq -rs '[.[][]]|map(select(has("name")))|map(select(.name|contains("dnsdist-")))|map(.version=(.name|ltrimstr("dnsdist-")))|map(select(true != (.version|contains("-"))))|map(.version)|"VERSION="+.[0]' > /tmp/latest-dnsdist-tag.sh && . /tmp/latest-dnsdist-tag.sh; } && \
    mkdir -v -m 0700 -p /root/.gnupg && \
    curl -RL -O 'https://dnsdist.org/_static/dnsdist-keyblock.asc' && \
    gpg2 --no-options --verbose --keyid-format 0xlong --keyserver-options auto-key-retrieve=true \
        --import *.asc && \
    curl -RL -O "https://downloads.powerdns.com/releases/dnsdist-${VERSION}.tar.bz2{.asc,.sig,}" && \
    gpg2 --no-options --verbose --keyid-format 0xlong --keyserver-options auto-key-retrieve=true \
        --verify *.sig && \
    rm -rf /root/.gnupg *.asc *.sig && \
    tar -xpf "dnsdist-${VERSION}.tar.bz2" && \
    rm -f "dnsdist-${VERSION}.tar.bz2" && \
    ( \
        cd "dnsdist-${VERSION}" && \
        ./configure \
          --sysconfdir=/etc/dnsdist \
          --mandir=/usr/share/man \
          --enable-dnscrypt \
          --enable-dns-over-tls \
          --with-libsodium \
          --with-re2 \
          --with-net-snmp && \
        make -j 2 && \
        make install-strip \
    )

FROM alpine:3

RUN apk --no-cache add \
      ca-certificates \
      curl \
      less \
      libedit \
      libsodium \
      lua-libs \
      net-snmp \
      openssl \
      protobuf \
      re2 && \
    rm -rf /var/cache/apk/*

ENV PAGER less

RUN addgroup -S dnsdist && \
    adduser -S -D -G dnsdist dnsdist

COPY --from=builder /usr/local/bin /usr/local/bin/
COPY --from=builder /usr/share/man/man1 /usr/share/man/man1/

RUN /usr/local/bin/dnsdist --version

ENTRYPOINT ["/usr/local/bin/dnsdist"]
CMD ["--help"]

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
