---
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - yamllint
