ARG VERSION=v3.1.0-ldap
FROM quay.io/netboxcommunity/netbox:${VERSION}

COPY requirements.txt /requirements.txt

RUN /opt/netbox/venv/bin/pip3 install --no-cache-dir -r /requirements.txt

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
