ARG VERSION=v3.4.8  # renovate: datasource=docker depName=quay.io/netboxcommunity/netbox
FROM quay.io/netboxcommunity/netbox:${VERSION}

COPY requirements.txt /requirements.txt
COPY files/launch.sh /opt/netbox/launch.sh

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      git \
    && /opt/netbox/venv/bin/pip3 install --no-cache-dir -r /requirements.txt \
    && chmod +x /opt/netbox/launch.sh \
    && apt-get remove -y \
      git \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

CMD [ "/opt/netbox/docker-entrypoint.sh", "/opt/netbox/launch.sh" ]

LABEL "org.opencontainers.image.documentation"="https://osism.github.io/docs/intro" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
