ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}

ARG USER_ID=45000
ARG GROUP_ID=45000

ENV DEBIAN_FRONTEND=noninteractive

USER root

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        git \
    && git clone https://github.com/sovereigncloudstack/metering /opt/app \
    && groupadd -g $GROUP_ID dragon \
    && useradd -g dragon -u $USER_ID -m -d /home/dragon dragon \
    && apt-get remove -y \
        git \
    && apt-get clean \
    && apt-get autoremove -y \
    && rm -rf \
      /var/lib/apt/lists/* \
      /var/tmp/*

WORKDIR /opt/app
RUN pip install -r requirements.txt

USER dragon
VOLUME ["/data"]
ENTRYPOINT ["python", "metersink", "-v"]

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"

