ARG GO_VERSION=1.22
FROM golang:$GO_VERSION-alpine AS build

ARG VERSION=1.1.0

RUN apk add --no-cache \
      bash \
      git \
      make \
    && mkdir -p "${GOPATH}/src/github.com/daimler"

WORKDIR ${GOPATH}/src/github.com/daimler
RUN git clone --depth 1 --branch v${VERSION} https://github.com/daimler/kosmoo.git

WORKDIR ${GOPATH}/src/github.com/daimler/kosmoo
RUN make build

FROM alpine:3

COPY --from=build /go/src/github.com/daimler/kosmoo/kosmoo /usr/bin/kosmoo

ENTRYPOINT ["/usr/bin/kosmoo", "-cloud-conf", "/etc/cloud.conf", "-kubeconfig", "/etc/kubeconfig"]
EXPOSE 9183

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
