FROM alpine:3.21

RUN apk add --no-cache rsync

ENTRYPOINT ["/usr/bin/rsync"]

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://recovery.quay.io/repository/osism/rsync" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
