ARG ALPINE_VERSION=3.23
FROM alpine:${ALPINE_VERSION}

COPY --chmod=0755 entrypoint.sh /entrypoint.sh

ENV USER_NAME=rsync
ENV USER_ID=1000
ENV GROUP_ID=1000

RUN apk update --no-cache \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      dumb-init \
      rsync \
      shadow \
    && addgroup -g ${GROUP_ID} ${USER_NAME} \
    && adduser -u ${USER_ID} -D -G ${USER_NAME} ${USER_NAME} \
    && mkdir /data /export \
    && chown -R ${USER_NAME}:${USER_NAME} /data /export

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/bin/rsync", "-avz", "/data/", "/export/root/"]
VOLUME ["/export"]

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://recovery.quay.io/repository/osism/rsync" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
