ARG PYTHON_VERSION=3.10
FROM python:${PYTHON_VERSION}-slim

ARG VERSION=3.0.1  # renovate: datasource=pypi depName=virtualbmc

ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1

COPY files/run.sh /run.sh

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3-dev libvirt-dev pkg-config gcc \
    && python3 -m pip --no-cache-dir install -U 'pip==23.0.1' \
    && python3 -m pip install --no-cache-dir virtualbmc==${VERSION} \
    && apt-get remove -y python3-dev libvirt-dev pkg-config gcc \
    && rm -rf /var/lib/apt/lists

CMD ["/run.sh"]

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
