ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-alpine

COPY files/requirements.txt /requirements.txt
COPY files/requirements.yml /requirements.yml
COPY files/run.sh /run.sh

RUN apk add --no-cache bash openssh-client sshpass \
    && apk add --no-cache --virtual .build-deps \
      build-base \
      cargo \
      git \
      libffi-dev \
      openssl-dev \
      python3-dev \
      rust \
    && pip3 --no-cache-dir install --upgrade 'pip==24.0' \
    && pip3 --no-cache-dir install -r /requirements.txt \
    && ansible-galaxy install -r /requirements.yml \
    && mkdir -p /opt/configuration/environments/manager \
    && apk del .build-deps

WORKDIR /opt/configuration/environments/manager

VOLUME ["/opt/configuration"]
ENTRYPOINT ["/run.sh"]

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
