FROM python:3.13-slim AS builder

COPY files/requirements.txt /requirements.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
      git \
      libffi-dev \
      libmariadb-dev \
      libssl-dev \
      libyaml-dev \
      pkg-config \
    && mkdir /wheels \
    && python3 -m pip install --no-cache-dir -U 'pip==24.3.1' \
    && python3 -m pip wheel --no-cache-dir --wheel-dir=/wheels --pre -r /requirements.txt \
    && python3 -m pip wheel --no-cache-dir --wheel-dir=/wheels "ara[server]"

FROM python:3.13-slim

ENV TZ=UTC

ADD --chmod=0755 https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

COPY --from=builder /wheels /wheels
COPY files/requirements.txt /requirements.txt
COPY files/run.sh /run.sh

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      curl \
      libmariadb3 \
    && python3 -m pip install --no-cache-dir -U 'pip==24.3.1' \
    && python3 -m pip install --no-cache-dir --no-index --find-links=/wheels --pre -r /requirements.txt \
    && python3 -m pip install --no-cache-dir --no-index --find-links=/wheels "ara[server]" \
    && useradd ara-server \
    && rm -rf /var/lib/apt/lists/* /wheels /requirements.txt

USER ara-server
WORKDIR /home/ara-server

EXPOSE 8000

CMD ["sh", "-c", "/wait && /run.sh"]
HEALTHCHECK CMD curl --fail http://localhost:8000 || exit 1

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
