FROM python:3.10-slim as builder

ARG VERSION=latest

COPY files/requirements.txt /requirements.txt

# hadolint ignore=DL3008,DL3013,SC2086
RUN echo $VERSION && apt-get update \
    && apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
      git \
      libffi-dev \
      libmariadb-dev \
      libssl-dev \
      libyaml-dev \
    && mkdir /wheels \
    && python3 -m pip install --no-cache-dir -U 'pip==22.1.1' \
    && python3 -m pip wheel --no-cache-dir --wheel-dir=/wheels -r /requirements.txt \
    && if [ $VERSION != "latest" ]; then python3 -m pip wheel --no-cache-dir --wheel-dir=/wheels "ara[server]==$VERSION"; else python3 -m pip wheel --wheel-dir=/wheels --no-cache-dir "git+https://github.com/ansible-community/ara"; fi

FROM python:3.10-slim

ARG VERSION=latest

ENV TZ=UTC

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

COPY --from=builder /wheels /wheels
COPY files/requirements.txt /requirements.txt
COPY files/run.sh /run.sh

# hadolint ignore=DL3008,DL3013,SC2102
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      curl \
      libmariadb3 \
    && python3 -m pip install --no-cache-dir -U 'pip==22.1.1' \
    && python3 -m pip install --no-cache-dir --no-index --find-links=/wheels -r /requirements.txt \
    && if [ $VERSION != "latest" ]; then python3 -m pip install --no-cache-dir --no-index --find-links=/wheels ara[server]; else python3 -m pip install --no-cache-dir --no-index --find-links=/wheels ara; fi \
    && useradd ara-server \
    && chmod +x /wait \
    && rm -rf /var/lib/apt/lists/* /wheels /requirements.txt

USER ara-server
WORKDIR /home/ara-server

EXPOSE 8000

CMD ["sh", "-c", "/wait && /run.sh"]
HEALTHCHECK CMD curl --fail http://localhost:8000 || exit 1

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
