# build stage
FROM node:lts-alpine as build-stage
ARG VERSION=v24.02.1  # renovate: datasource=github-releases depName=bastienwirtz/homer

WORKDIR /app

ADD https://github.com/bastienwirtz/homer/archive/refs/tags/${VERSION}.tar.gz /app
RUN tar xvzf ${VERSION}.tar.gz
RUN mv /app/homer-* /app/homer  # ugly, but allows us to ditch the hussle with docker tags containing "v" or not.

WORKDIR /app/homer

RUN yarn install --frozen-lockfile \
    && yarn build

# production stage
FROM alpine:3.19

ENV USER darkhttpd
ENV GROUP darkhttpd
ENV GID 911
ENV UID 911
ENV PORT 8080

RUN addgroup -S ${GROUP} -g ${GID} && adduser -D -S -u ${UID} ${USER} ${GROUP} && \
    apk add -U --no-cache su-exec darkhttpd

COPY --from=build-stage --chown=${USER}:${GROUP} /app/homer/dist /www/
COPY --from=build-stage --chown=${USER}:${GROUP} /app/homer/dist/assets /www/default-assets
COPY files/entrypoint.sh /entrypoint.sh
COPY files/*.png /www/

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:${PORT}/ || exit 1

EXPOSE ${PORT}
VOLUME /www/assets
ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
