---
roles:
  - name: geerlingguy.dotfiles
    type: git
    src: git+https://github.com/geerlingguy/ansible-role-dotfiles
  - name: hardening
    type: git
    src: git+https://github.com/openstack/ansible-hardening

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: kubernetes.core
  - name: netbox.netbox
  - name: openstack.cloud
  - name: osism.commons
  - name: osism.playbooks
  - name: osism.services
  - name: osism.validations
  - name: debops.debops
