---
roles:
  - name: geerlingguy.dotfiles
    type: git
    src: git+https://github.com/geerlingguy/ansible-role-dotfiles
  - name: hardening
    type: git
    src: git+https://github.com/openstack/ansible-hardening

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: containers.podman
  - name: debops.debops
  - name: kubernetes.core
  - name: netbox.netbox
  - name: openstack.cloud
  - name: osism.manager
  - name: osism.playbooks
  - name: https://github.com/osism/ansible-collection-commons.git
    type: git
    version: main
  - name: https://github.com/osism/ansible-collection-services.git
    type: git
    version: main
  - name: https://github.com/osism/ansible-collection-validations.git
    type: git
    version: main
