FROM python:3.12-slim AS builder

COPY files/requirements.txt /requirements.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
    && mkdir /wheels \
    && python3 -m pip install --no-cache-dir -U 'pip==24.2' \
    && python3 -m pip wheel --no-cache-dir --wheel-dir=/wheels --pre -r /requirements.txt

FROM python:3.12-slim

COPY --from=builder /wheels /wheels
COPY files/* /

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      git \
    && python3 -m pip install --no-cache-dir -U 'pip==24.2' \
    && python3 -m pip install --no-cache-dir --no-index --find-links=/wheels --pre -r /requirements.txt \
    && ansible-galaxy collection install -r /requirements.yml \
    && ansible-galaxy role install -r /requirements.yml \
    && apt-get remove -y \
      git \
    && apt-get autoremove -y \
    && mkdir -p /zuul \
    && rm -rf \
      /wheels \
      /requirements.txt \
      /requirements.yml \
      /var/lib/apt/lists/* \
      /var/tmp/* \
    && pip install --no-cache-dir pyclean==3.0.0 \
    && pyclean /usr \
    && pip uninstall -y pyclean

VOLUME ["/zuul"]
ENTRYPOINT ["/run.sh"]

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
