FROM golang:alpine3.20 AS builder

RUN apk --update --no-cache add git \
    && go get -u github.com/cloudflare/goflow

FROM alpine:3.20.2

RUN apk update --no-cache \
    && adduser -S -D -H -h / flow

USER flow
COPY --from=builder /go/bin/goflow /

ENTRYPOINT ["./goflow"]
