ARG DEBIAN_VERSION=bookworm
FROM debian:${DEBIAN_VERSION}

ARG VERSION=reef

ARG USER_ID=45000
ARG GROUP_ID=45000

ENV DEBIAN_FRONTEND=noninteractive

USER root

COPY files/run.sh /run.sh

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        apt-transport-https \
        bash-completion \
        dumb-init \
        gnupg2 \
        software-properties-common \
        wget \
    && wget -q -O- https://download.ceph.com/keys/release.asc | apt-key add - \
    && if [ $VERSION = "quincy" ]; then apt-add-repository --yes "deb https://download.ceph.com/debian-quincy/ bullseye main"; fi \
    && if [ $VERSION = "reef" ]; then add-apt-repository --yes -c main -U https://download.ceph.com/debian-reef/; add-apt-repository --yes -c main -U https://download.ceph.com/debian-reef/; fi \
    && if [ $VERSION = "squid" ]; then add-apt-repository --yes -c main -U https://download.ceph.com/debian-squid/; add-apt-repository --yes -c main -U https://download.ceph.com/debian-squid/; fi \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        ceph-common \
        fio \
    && if [ $VERSION = "squid" ]; then apt-get install --no-install-recommends -y ceph-base; fi \
    && groupadd -g $GROUP_ID dragon \
    && useradd -g dragon -u $USER_ID -m -d /home/dragon dragon \
    && if [ ! -e /etc/bash_completion.d/ ]; then \
          mkdir -p /etc/bash_completion.d; \
          cp /usr/share/bash-completion/completions/ceph /etc/bash_completion.d/ceph; \
          cp /usr/share/bash-completion/completions/rados /etc/bash_completion.d/rados; \
          cp /usr/share/bash-completion/completions/radosgw-admin /etc/bash_completion.d/radosgw-admin; \
          cp /usr/share/bash-completion/completions/rbd /etc/bash_completion.d/rbd; \
       fi \
    && apt-get remove -y \
        apt-transport-https \
        software-properties-common \
        wget \
    && apt-get clean \
    && apt-get autoremove -y \
    && mkdir /configuration \
    && rm -rf \
      /var/lib/apt/lists/* \
      /var/tmp/*

USER dragon

VOLUME ["/etc/ceph"]

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/run.sh"]

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
