ARG DEBIAN_VERSION=bullseye
FROM debian:${DEBIAN_VERSION}

ARG VERSION=octopus

ARG USER_ID=45000
ARG GROUP_ID=45000

ENV DEBIAN_FRONTEND=noninteractive

USER root

COPY files/run.sh /run.sh

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        apt-transport-https \
        bash-completion \
        dumb-init \
        gnupg2 \
        software-properties-common \
        wget \
    && wget -q -O- https://download.ceph.com/keys/release.asc | apt-key add - \
    && apt-add-repository "deb https://download.ceph.com/debian-$VERSION/ bullseye main" \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        ceph \
        fio \
    && groupadd -g $GROUP_ID dragon \
    && useradd -g dragon -u $USER_ID -m -d -l /home/dragon dragon \
    && apt-get remove -y \
        apt-transport-https \
        software-properties-common \
        wget \
    && apt-get clean \
    && apt-get autoremove -y \
    && mkdir /configuration \
    && rm -rf \
      /var/lib/apt/lists/* \
      /var/tmp/*

USER dragon

VOLUME ["/etc/ceph"]

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/run.sh"]

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
