# source: https://github.com/clearlinux/dockerfiles/blob/master/cgit/Dockerfile

FROM ghcr.io/clearlinux/httpd:latest AS httpd
FROM clearlinux:latest AS builder

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG swupd_args
# Move to latest Clear Linux release to ensure
# that the swupd command line arguments are
# correct
RUN swupd update --no-boot-update $swupd_args

# Grab os-release info from the minimal base image so
# that the new content matches the exact OS version
COPY --from=httpd /usr/lib/os-release /

# Install additional content in a target directory
# using the os version from the minimal base
# hadolint ignore=SC1091
RUN source /os-release && \
    mkdir /install_root \
    && swupd os-install -V "${VERSION_ID}" \
    --path /install_root --statedir /swupd-state \
    --bundles=sudo,curl,scm-server,httpd --no-boot-update

# For some Host OS configuration with redirect_dir on,
# extra data are saved on the upper layer when the same
# file exists on different layers. To minimize docker
# image size, remove the overlapped files before copy.
RUN mkdir /os_core_install
COPY --from=httpd / /os_core_install/

WORKDIR /
RUN find os_core_install | sed -e 's/os_core_install/install_root/' | xargs rm -d &> /dev/null || true

FROM ghcr.io/clearlinux/httpd:latest

COPY --from=builder /install_root /
COPY cgitrc /etc/cgitrc
COPY httpd-cgit.conf /etc/httpd/conf.d/httpd-cgit.conf

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
