ARG PYTHON_VERSION=3.10
FROM python:${PYTHON_VERSION}-alpine

ARG VERSION=latest

COPY files/config.yml /config.yml
COPY files/requirements.txt /requirements.txt

RUN apk add --no-cache --virtual .build-deps \
      git \
    && apk add --no-cache \
      dumb-init \
    && pip3 install --no-cache-dir -r /requirements.txt \
    && pip3 install --no-cache-dir git+https://github.com/tibeer/arista-eos-exporter \
    && apk del .build-deps

ENTRYPOINT ["usr/bin/dumb-init", "--", "python", "/usr/local/bin/main.py", "-c", "/config.yml"]

LABEL "org.opencontainers.image.documentation"="https://docs.osism.tech" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://www.osism.tech" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
