---
name: Build goflow container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-goflow-container-image.yml
      - goflow/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-goflow-container-image.yml
      - goflow/**

jobs:

  build-goflow-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: goflow
          REPOSITORY: osism/goflow

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: goflow
          REPOSITORY: osism/goflow
        if: |
          github.repository == 'osism/container-images' &&
          github.ref == 'refs/heads/main'
