---
name: Build lloadd container image

"on":
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-lloadd-container-image.yml
      - lloadd/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-lloadd-container-image.yml
      - lloadd/**

jobs:

  build-lloadd-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 2.6.8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: lloadd
          REPOSITORY: osism/lloadd
          VERSION: ${{ matrix.version }}

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: lloadd
          REPOSITORY: osism/lloadd
          VERSION: ${{ matrix.version }}
        if: |
          github.repository == 'osism/container-images' &&
          github.ref == 'refs/heads/main'
