---
name: Build awxclient container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-awxclient-container-image.yml
      - awxclient/**
  pull_request:
    paths:
      - .github/workflows/build-awxclient-container-image.yml
      - awxclient/**

jobs:

  build-awxclient-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 19.5.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: awxclient
          REPOSITORY: osism/awxclient
          VERSION: ${{ matrix.version }}

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: awxclient
          REPOSITORY: osism/awxclient
          VERSION: ${{ matrix.version }}
        if: |
          github.repository == 'osism/container-images' &&
          github.ref == 'refs/heads/main'
