---
name: Build aptly prepare container image

"on":
  workflow_dispatch:
    schedule:
      - cron: "0 3 * * *"
  push:
    branches:
      - 'main'
    paths:
      - 'aptly/'
      - '.github/workflows/build-aptly-prepare-container-image.yml'

jobs:
  build-aptly-prepare-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: aptly-prepare
          REPOSITORY: osism/aptly-prepare
          BUILD_OPTS: --build-context ./aptly --file Containerfile-prepare

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE: aptly-prepare
          REPOSITORY: osism/aptly-prepare
        if: |
          github.repository == 'osism/container-images' &&
          github.ref == 'refs/heads/main'
