---
name: Build gnmic container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-gnmic-container-image.yml
      - scrips/build.sh
      - gnmic/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-gnmic-container-image.yml
      - scrips/build.sh
      - gnmic/**

jobs:

  build-gnmic-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 0.41.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.9.2

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: gnmic
          REPOSITORY: osism/gnmic
          VERSION: ${{ matrix.version }}

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
          DTRACK_SERVER: ${{ secrets.DTRACK_SERVER }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: gnmic
          REPOSITORY: osism/gnmic
          VERSION: ${{ matrix.version }}
        if: |
          github.repository == 'osism/container-images' &&
          github.ref == 'refs/heads/main'
