---
name: Build metering container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-metering-container-image.yml
      - metering/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-metering-container-image.yml
      - metering/**

jobs:

  build-metering-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - zed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: metering
          REPOSITORY: osism/metering
          VERSION: ${{ matrix.version }}

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE: metering
          REPOSITORY: osism/metering
          VERSION: ${{ matrix.version }}
        if: |
          github.repository == 'osism/container-images' &&
          github.ref == 'refs/heads/main'
