ARG PYTHON_VERSION=3.13
FROM python:${PYTHON_VERSION}-alpine

ARG VERSION=caracal

ARG USER_ID=45000
ARG GROUP_ID=45000

COPY files/requirements.txt /requirements.txt
COPY files/requirements.extra.txt /requirements.extra.txt

# This solves the following problem. It can be removed in the future if
# netifaces is no longer used as a dependency of the OpenStack SDK.
#
# netifaces.c:1808:9: error: initialization of 'int' from 'void *' makes
# integer from pointer without a cast [-Wint-conversion]
ENV CFLAGS="-Wno-int-conversion"

RUN apk update --no-cache \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      dumb-init \
      libstdc++ \
    && apk add --no-cache --virtual .build-deps \
      build-base \
      cargo \
      libffi-dev \
      openssl-dev \
      python3-dev \
      rust \
    && if [ $VERSION = "epoxy" ]; then wget -q -P / -O requirements.tar.gz https://tarballs.opendev.org/openstack/requirements/requirements-master.tar.gz; fi \
    && if [ $VERSION = "dalmatian" ]; then wget -q -P / -O requirements.tar.gz https://tarballs.opendev.org/openstack/requirements/requirements-stable-2024.2.tar.gz; fi \
    && if [ $VERSION = "caracal" ]; then wget -q -P / -O requirements.tar.gz https://tarballs.opendev.org/openstack/requirements/requirements-stable-2024.1.tar.gz; fi \
    && if [ $VERSION = "bobcat" ]; then wget -q -P / -O requirements.tar.gz https://tarballs.opendev.org/openstack/requirements/requirements-stable-2023.2.tar.gz; fi \
    && if [ $VERSION = "antelope" ]; then wget -q -P / -O requirements.tar.gz https://tarballs.opendev.org/openstack/requirements/requirements-stable-2023.1.tar.gz; fi \
    && mkdir /requirements \
    && tar xzf /requirements.tar.gz -C /requirements --strip-components=1 \
    && rm -rf /requirements.tar.gz \
    && while read -r package; do \
         grep -q "$package" /requirements/upper-constraints.txt && \
         echo "$package" >> /packages.txt || true; \
       done < /requirements.txt \
    && pip3 --no-cache-dir install uv \
    && uv pip install \
      -r /packages.txt \
      -c /requirements/upper-constraints.txt \
      --system \
    && uv pip install \
      -r /requirements.extra.txt \
      -c /requirements/upper-constraints.txt \
      --system \
    && rm -rf \
      /packages.txt \
      /requirements \
      /requirements.txt \
      /requirements.extra.txt \
    && apk del .build-deps \
    && openstack complete > /osc.bash_completion \
    && pyclean /usr \
    && addgroup -g $GROUP_ID dragon \
    && adduser -D -u $USER_ID -G dragon dragon \
    && mkdir /configuration \
    && chown -R dragon: /configuration

USER dragon
WORKDIR /configuration

VOLUME ["/configuration"]

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["openstack"]

LABEL "org.opencontainers.image.documentation"="https://osism.tech/docs/" \
      "org.opencontainers.image.licenses"="ASL 2.0" \
      "org.opencontainers.image.source"="https://github.com/osism/container-images" \
      "org.opencontainers.image.url"="https://quay.io/organization/osism" \
      "org.opencontainers.image.vendor"="OSISM GmbH"
